<!DOCTYPE html>
<html lang="fr">
<head>
    <title>Login</title>
</head>
<body>
    <h2>Connexion</h2>
    <form method="post" action="controller_log.php">
        <label for="nom_utilisateur">Nom d'utilisateur :</label>
        <input type="text" name="nom_utilisateur" required><br><br>
        <label for="mot_de_passe">Mot de passe :</label>
        <input type="password" name="mot_de_passe" required><br><br>
        <input type="submit" value="Se connecter">
    </form>
</body>
</html>

