
<!-- <form class="box" action="" method="post" name="login">
<h1 class="box-title">Connexion</h1>
<input type="text" class="box-input" name="username" placeholder="Nom d'utilisateur">
<input type="password" class="box-input" name="password" placeholder="Mot de passe">
<input type="submit" value="Connexion " name="submit" class="box-button">
<p class="box-register">Vous êtes nouveau ici? <a href="register.php">S'inscrire</a></p>
<php if (! empty($message)) { ?>
    <p class="errorMessage"><php echo $message; ?></p>
<php } ?>
</form> -->


<!-- <php

// Validation du formulaire
if (isset($_POST['email']) &&  isset($_POST['password'])) {
    $db = connectDB();
    foreach ($users as $user) {
        if (
            $user['mail'] === $_POST['mail'] &&
            $user['password'] === $_POST['password']
        ) {
            $loggedUser = [
                'mail' => $user['mail'],
            ];
        } else {
            $errorMessage = sprintf('Les informations envoyées ne permettent pas de vous identifier : (%s/%s)',
                $_POST['mail'],
                $_POST['password']
            );
        }
    }
}
?>


<!-- // Si utilisateur/trice est non identifié(e), on affiche le formulaire -->

<!-- <php if(!isset($loggedUser)): ?>
<form action="home.php" method="post">
    <! // si message d'erreur on l'affiche -->
    <!-- ?php if(isset($errorMessage)) : ?>
        <div class="alert alert-danger" role="alert">
            <php echo $errorMessage; ?>
        </div>
    <php endif; ?>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email" aria-describedby="email-help" placeholder="you@exemple.com">
        <div id="email-help" class="form-text">L'email utilisé lors de la création de compte.</div>
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Mot de passe</label>
        <input type="password" class="form-control" id="password" name="password">
    </div>
    <button type="submit" class="btn btn-primary">Envoyer</button>
</form> -->

<!-- // Si utilisateur/trice bien connectée on affiche un message de succès -->

<!-- <php else: ?>
    <div class="alert alert-success" role="alert">
        Bonjour <php echo $loggedUser['mail']; ?> et bienvenue sur le site !
    </div>
<php endif; ?> -->


<form method="post" action="controller_login_test.php">
        <label for="mail">E-mail :</label>
        <input type="text" name="nom_utilisateur" required><br><br>
        <label for="password">Mot de passe :</label>
        <input type="password" name="password" required><br><br>
        <input type="submit" value="Se connecter">
    </form>

