<!-- <h1>CONTACT</h1>
<h2>Creer un utilisateur</h2>
<form method="POST">
        <input type="text" class="form-control" name="name" placeholder="name">
        <br>
        <input type="text" class="form-control" name="firstName" placeholder="first name">
        <br>
        <input type="mail" class="form-control" name="mail" placeholder="mail">
        <br>
        <input type="text" class="form-control" name="password" placeholder="password">
        <br>
        <input type="submit" class="btn btn-primary" value="creer" name="creer">
    </form> -->
<!-- ////////////////////////////////////////////////////////////////////////////////////// -->

<form method="post">

  <h1 class="box-title">S'inscrire</h1>
  <input type="mail" class="form-control" name="mail" placeholder="Email" required />
  <input type="password" class="form-control" name="password" placeholder="Mot de passe" required />
  <input type="submit" name="creer" value="S'inscrire" class="btn btn-primary" />
  <p class="box-register">Déjà inscrit? <a href="template_login.phtml">Connectez-vous ici</a></p>
</form>



<!-- ////////////////////////////////////////////////////////////////////////////////////// -->
<!-- <h2>Ajouter un poste</h2>
<form method="POST">
<div class="mb-3">
  <label for="title" class="form-label">Title</label>
  <input type="text" class="form-control" name="title" id="title" placeholder="Title">
</div>
<div class="mb-3">
  <label for="description" class="form-label">Description</label>
  <input type="text" class="form-control" name="description" id="description" placeholder="Description">
</div>
<div class="mb-3">
  <label for="src" class="form-label">Source</label>
  <input type="text" class="form-control" name="src" id="src" placeholder="URL Source">
</div>
<div class="mb-3">
  <label for="author" class="form-label">Author</label>
  <input type="text" class="form-control" name="author" id="author" placeholder="Author">
</div>
<div class="mb-3">
  
  <input type="submit" class="btn btn-primary" name="submit" value="Add Picture">
</div>
</form> -->